# Default values for chatgpt-platform
replicaCount: 1

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

frontend:
  name: frontend
  image:
    repository: chatgpt-frontend
    tag: latest
  service:
    type: NodePort
    port: 80
    targetPort: 3000
    nodePort: 30080
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

backend:
  name: backend
  image:
    repository: chatgpt-backend
    tag: latest
  service:
    type: ClusterIP
    port: 80
    targetPort: 3001
  env:
    MISTRAL_API_URL: "http://host.docker.internal:1234"
    PORT: "3001"
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: chatgpt-local.dev
      paths:
        - path: /
          pathType: Prefix
  tls: []

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}
tolerations: []
affinity: {}