apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: chatgpt-platform-backend-monitor
  namespace: chatgpt-monitoring
  labels:
    app: chatgpt-platform
    component: backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: chatgpt-platform
      app.kubernetes.io/component: backend
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s