apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chatgpt-platform.fullname" . }}-backend
  labels:
    {{- include "chatgpt-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chatgpt-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "chatgpt-platform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: {{ .Values.backend.name }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.targetPort }}
              protocol: TCP
          env:
            - name: MISTRAL_API_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "chatgpt-platform.fullname" . }}-config
                  key: MISTRAL_API_URL
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "chatgpt-platform.fullname" . }}-config
                  key: PORT
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10